version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running unit tests
      - python -m pytest -q

  build:
    commands:
      - echo Packaging artifact
      - zip -r blacklist-app.zip . -x "*.git*" "*__pycache__*" "*.pyc" ".env*" "tests/*" "postman/*" "migrations/*" ".venv/*"

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - blacklist-app.zip
  discard-paths: yes
